[StaticTorqueServiceOptions]
Host=127.0.0.1
Port=502

[Parameters:0]
# 按照目标扭矩小于等于TargetUnder来选择参数集。配置了多个相同TargetUnder的参数集时，序号大的生效
TargetUnder=15
# 大于等于目标扭矩*BeginThreshold开始采集数据，经过EndTimeSpan时间后结束采集
# 如果没有设置EndTimeSpan，则小于目标扭矩*EndThreshold时结束采集
# 结束采集后需间隔Interval才可能开始下一次采集
# 采集的数据保存到results文件夹，数据中找出的所有峰值保存到-peaks.txt中
BeginThreshold=0.3
EndTimeSpan=00:00:03
EndThreshold=0.2
Interval=00:00:00
# 采集的数据去掉开头BeginSkip个和结尾EndSkip个数据后再分析峰值
BeginSkip=3
EndSkip=3
# 扭矩 = a * 数字量 + b，以下注释的是a与b的默认值
# a=根据传感器灵敏度计算的理论值
# b=0
# 若设置了a则无视传感器灵敏度
Sensitivity=0.1144

[Parameters:1]
# 无穷大可以保证目标扭矩最终能匹配到参数集，如果没有这一项，当目标扭矩大于所有已配置的参数集时，提示错误：没有适合目标的参数集
TargetUnder=Infinity
BeginThreshold=0.3
EndTimeSpan=00:00:03
EndThreshold=0.2
Interval=00:00:00
BeginSkip=3
EndSkip=3
Sensitivity=0.1144

[ConnectionStrings]
MES="Password=mes_public;Persist Security Info=True;User ID=mes_public;Data Source=(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = sumesdb.inovance.cn)(PORT = 1522)))(CONNECT_DATA = (SERVICE_NAME = mes)))"
